### ISSUE TITLE
[Bug]: Can't install package with Laravel 8

### ISSUE THREAD

**Issue by bigcandy95** [kiwilan/php-ebook#54]
### What happened?

I can't install package 
![Screen Shot 2023-12-06 at 14 03 50](https://github.com/kiwilan/php-ebook/assets/73579569/4d8cdf04-01ad-4d79-a093-d959e889f3ec)

### How to reproduce the bug

Run composer require kiwilan/php-ebook

### Package Version

2.1.02

### PHP Version

8.2

**Comment by ewilan-riviere** [comment]
Thanks for this report!

With flat `-W`, can you force update?

### Cause

[`kiwilan/php-ebook`](https://github.com/kiwilan/php-ebook) use [`kiwilan/php-archive`](https://github.com/kiwilan/php-archive) to handle multiple archive types. In this package, I use [``](https://github.com/symfony/process) to handle [7z](https://www.7-zip.org/) archives.

I can't use anterior version of `symfony/process` because it's a [`pestphp/pest`](https://github.com/pestphp/pest) dependency.

### Solution

I can change support for 7z archives of `php-archive` but it's an heavy process.

**Comment by ewilan-riviere** [comment]
Can you update to last version, I drop symfony/process.

**Comment by ewilan-riviere** [comment]
Considered as done.
